-- CreateTable
CREATE TABLE "Pokedex" (
    "NUMERO" INTEGER NOT NULL,
    "NOM" TEXT,
    "TYPE_1" TEXT,
    "TYPE_2" TEXT,
    "POINTS_DE_VIE" INTEGER,
    "NIVEAU_ATTAQUE" INTEGER,
    "NIVEAU_DEFENSE" INTEGER,
    "NIVEAU_ATTAQUE_SPECIALE" INTEGER,
    "NIVEAU_DEFENSE_SPECIALE" INTEGER,
    "VITESSE" INTEGER,
    "GENERATION" INTEGER,
    "LEGENDAIRE" BOOLEAN,

    CONSTRAINT "Pokedex_pkey" PRIMARY KEY ("NUMERO")
);

-- CreateTable
CREATE TABLE "Task" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "date" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'En cours',
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "ownerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
